services: 
  master:
    image: alpine:latest
    container_name: master-node
    hostname: master-node
    command: sh -c "echo 'Master node executando.' && sleep infinity"

  worker1:
    image: alpine:latest
    container_name: workerl-node
    hostname: workerl-node
    command: sh -c "echo 'worker node 1 executando.' && sleep infinity"

  worker2:
    image: alpine:latest
    container_name: worker2-node
    hostname: worker2-node
    command: sh -c "echo 'worker node 2 executando.' && sleep infinity"




