version: '3.8'

services: 
  master:
    image: alpine:latest
    container_name: master-node
    hostname: master-node
    command: sh -c "echo 'Master-node executando.' && sleep infinity" 
  
  worker1:
    image: alpine:latest
    container_name: worker1-node
    hostname: worker1-node
    command: sh -c "echo 'worker1-node executando.' && sleep infinity" 

  worker2:
    image: alpine:latest
    container_name: worker2-node
    hostname: worker2-node
    command: sh -c "echo 'worker2-node executando.' && sleep infinity" 